### ISSUE TITLE
docker  image can`t  start

### ISSUE THREAD

**Issue by longtong99** [opensourcecobol/opensourcecobol4j#190]
hi,can you give the docker image start common,i pull docker image success,but can't start it,thanks

**Comment by yutaro-sakamoto** [comment]
@longtong99
Please try the following commands.
```shell
docker pull opensourcecobol/opensourcecobol4j:1.0.12
docker run -itd --name cobol4j opensourcecobol/opensourcecobol4j:1.0.12
docker attach cobol4j
```
Then you will be able to use the `cobj` command.

**Comment by longtong99** [comment]
thanks，it works
