### ISSUE TITLE
Support JDK8

### ISSUE THREAD

**Issue by yutaro-sakamoto** [opensourcecobol/opensourcecobol4j#196]
Perform tests with JDK8 failed.
https://github.com/yutaro-sakamoto/opensourcecobol4j/actions/runs/5711534644/job/15473328921

opensource COBOL 4J should support JDK8 and we should determine the supported JDK versions.

**Comment by R1310328554** [comment]
Could anyone tell me what JDK versions are supported ...  JDK8 is failed on my laptop

**Comment by yutaro-sakamoto** [comment]
Please try OpenJDK 17.
opensource COBOL 4J v1.0.14 is tested with OpenJDK 17.
