### ISSUE TITLE
LICENSE upgrade to (L)GPLv3+

### ISSUE THREAD

**Issue by GitMensch** [opensourcecobol/opensourcecobol4j#22]
Is there a reason for you to keep the license at the current version? It would be easier to share sources between this project and GnuCOBOL if the license would be identical; otherwise GC can integrate changes from this project, but not the other way around.

**Comment by ytr-sakamoto** [comment]
Thank you for your suggestion.
We are considering upgrading the license to LGPLv3 in the next update.

**Comment by ytr-sakamoto** [comment]
Yesterday we updated opensource COBOL 4j but the license was not changed.
We will update the license in the near future.

**Comment by GitMensch** [comment]
Thank you for the note. Do you consider the same for opensourcecobol and the esql preprocessor?

**Comment by ytr-sakamoto** [comment]
We will update the license of opensource COBOL to GPL3 in the next version.
We consider the same for Open-COBOL-ESQL.

**Comment by ytr-sakamoto** [comment]
We upgraded the license to GPL3 in v1.0.2.

**Comment by GitMensch** [comment]
Thank you! Note: It seems that without intend the FDL and LGPL were deleted, too.
The files so far under FDL can likely be dropped altogether (#30), otherwise you may likely want to add the [FDL](http://www.gnu.org/licenses/fdl.md) back.
The files in libcobj still say LGPL so it is likely reasonable to include [the LGPLv3](http://www.gnu.org/licenses/lgpl-3.0.md) as lgpl-3.0.md or LICENSE.LIB or COPYING.LIB or LGPLv3 in this repo.

**Comment by GitMensch** [comment]
Last open points fixed with 1451d434d5c1d330036ae1ff4392ce903f7eedbd an 143e01c1880212279101ddff08edacd0cd53c0fb.
