### ISSUE TITLE
Support for TRIM Function

### ISSUE THREAD

**Issue by ppputtyo** [opensourcecobol/opensourcecobol4j#243]
When converting COBOL code containing the TRIM function to Java, the following error occurs:
```sh
error: cannot find symbol
          CobolTerminal.display (0, 1, 1, CobolIntrinsic.funcTrim (0, 0, f_SAMPLE, 0));
                                                        ^
symbol:   method funcTrim(int,int,AbstractCobolField,int)
location: class CobolIntrinsic
1 error
```
It appears that this issue is due to the absence of the `funcTrim` method in the `CobolIntrinsic` class of the `libcobj`.

## Reproduction
Environment: Ubuntu 22.04 (WSL)

Code
```cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. SAMPLE.

DATA DIVISION.
    WORKING-STORAGE SECTION.
        01 SAMPLE PIC X(6).  
PROCEDURE DIVISION.
    MAIN SECTION.
        MOVE " HELLO" TO SAMPLE.       
        DISPLAY SAMPLE.                
        DISPLAY FUNCTION TRIM(SAMPLE). 
```

Command
```sh
cobj -free sample.cbl
```

Thank you!

**Comment by yutaro-sakamoto** [comment]
@ppputtyo 
Thank you for your valuable suggestion.
I will release opensource COBOL 4J v1.0.16, which supports the function `TRIM`, on October 31st.
If you find problems or would like us to implement new features, do not hesitate to post issues.

**Comment by ppputtyo** [comment]
Thank you for the update!
