### ISSUE TITLE
The installation command in the wiki is wrong.

### ISSUE THREAD

**Issue by ppputtyo** [opensourcecobol/opensourcecobol4j#247]
I think chapter [Install opensource COBOL 4J](https://github.com/opensourcecobol/opensourcecobol4j/wiki/Install-opensource-COBOL-4j-v1.0.16#install-opensource-cobol-4j) in the wiki installation instructions is wrong and the following command is correct.
Please confirm.

```diff
curl -L -o opensourcecobol4j-v1.0.16.tar.gz https://github.com/opensourcecobol/opensourcecobol4j/archive/refs/tags/v1.0.16.tar.gz
tar zxvf opensourcecobol4j-v1.0.16.tar.gz
- cd opensourcecobol4j-v1.0.16
+ cd opensourcecobol4j-1.0.16
./configure --prefix=/usr/
make
sudo make install
```

Thank you.

**Comment by yutaro-sakamoto** [comment]
I have fixed the commands in all installation manuals.
Thank you!
