### ISSUE TITLE
FR: Keep a Changelog

### ISSUE THREAD

**Issue by GitMensch** [opensourcecobol/opensourcecobol4j#25]
It seems that a lot of good things happen here - but I can't easily find out about those because the commit logs are all in Japanese.
I see that an "old style" Changelog in every folder may match this project, but a single one which is added to with each commit would be very helpful. For some motivations and suggestions concerning the format see https://keepachangelog.com/ (or https://keepachangelog.com/ja/)

I think a CHANGELOG.md or would be very helpful in general and also can be linked in the README.md.
For CHANGELOG_JP.md `git log` (or the [online version](https://github.com/opensourcecobol/opensourcecobol4j/commits/develop)) can be used.

**Comment by GitMensch** [comment]
@yutaro-sakamoto: I still think that's both reasonable and important. If you don't think so feel free to "close as not planned".

**Comment by yutaro-sakamoto** [comment]
@GitMensch 
Thank you for reminding us.
Also, we apologize for the delay in responding.
We will review all pull requests in the next week.

**Comment by yutaro-sakamoto** [comment]
I added CHANGELOG.md.
Thank you for your suggestion.
