### ISSUE TITLE
Instruction to output the java file

### ISSUE THREAD

**Issue by hungpchu** [opensourcecobol/opensourcecobol4j#26]
In the picture below, when we run the `cobc -m [COBOL source file]` command, README says that `("cobc" command produces [PROGRAM-ID].java and [PROGRAM-ID].class in the current directory.)`. However, from the picture below, the command `cobc -m <filename>.cob` will produce <filename>.dylib. Can you give me more detailed guide on the correct command to output the java file?
<img width="1129" alt="Screen Shot 2021-09-02 at 4 09 56 PM" src="https://user-images.githubusercontent.com/25466693/131916758-4e5de121-c5a5-4575-a5fc-99e1a47981c3.png">
<img width="1350" alt="Screen Shot 2021-09-02 at 4 10 56 PM" src="https://user-images.githubusercontent.com/25466693/131916777-71bbd8cd-ef9e-4522-a543-c4c357777262.png">

**Comment by ytr-sakamoto** [comment]
Currently, the recommended installation way is using Docker (see [the installation page](https://github.com/opensourcecobol/opensourcecobol4j/wiki/Installation(Docker)))
In the docker container, cobc command will produce .java and .class files.
We will make installation manuals for other platforms in the future.
