### ISSUE TITLE
Is "libcob" directory still used? If not: delete.

### ISSUE THREAD

**Issue by GitMensch** [opensourcecobol/opensourcecobol4j#31]
The license change also deleted the LGPL file (which is discussed in the related issue) this folder is under.
In general I do wonder: is it actually still used? If only partial I'd suggest to delete the unused parts, if "not at all" please get rid of it.

**Comment by yutaro-sakamoto** [comment]
We removed libcob/ directory when we released opensource COBOL 4J v1.0.5
https://github.com/opensourcecobol/opensourcecobol4j/releases/tag/v1.0.5

**Comment by GitMensch** [comment]
Fixed by 86926bd37e006330521990fadf26263a0239b806.
