### ISSUE TITLE
Use Gradle or Maven to manage java source code

### ISSUE THREAD

**Issue by yutaro-sakamoto** [opensourcecobol/opensourcecobol4j#37]
Prior to v1.0.3, we execute javac command to compile java source code.
We use Gradle or Maven to manage libcobj/.

**Comment by asusjtc** [comment]
Good Morning Mr. Yutaro-sakamoto.
Would you please let me know which version of java jdk or jre is suitable to install cobol4j ?.
I am using Ubuntu 22-04, with java-11; and the "make" process terminates abnormally with messages of java deprecated instructions.
So I guess that java 11 should not be used, but can you tell me which java version to use ?.

**Comment by yutaro-sakamoto** [comment]
Sorry for the delay in replying.
Perhaps what you are seeing is a message like the following.
```
Note: src/jp/osscons/opensourcecobol/libcobj/call/CobolResolve.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
Even with this message, the make command should complete.

Even with Ubuntu 22.04 and Java 11 installed, if you ignore this message, you should be able to use opensource COBOL 4j without any problems.

We see this problem as an issue that should be resolved in the next version or later.

**Comment by hanohrs** [comment]
Is it OK to make a pull request to use Maven? Or, do you prefer Gradle?

**Comment by yutaro-sakamoto** [comment]
I prefer Maven.

**Comment by hanohrs** [comment]
I see. Thank you.
