### ISSUE TITLE
EXIT PERFORM causes Segmentation Fault

### ISSUE THREAD

**Issue by hanohrs** [opensourcecobol/opensourcecobol4j#45]
Compiling the following program fails with Segmentation Fault.

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. EXITPERF.
       PROCEDURE DIVISION.
           PERFORM FOREVER
             EXIT PERFORM
           END-PERFORM.
           STOP RUN.
```

**Comment by yutaro-sakamoto** [comment]
We solved the problem in 3e85cee36876d27abdeb5a0fb6fe1bb97bdc7a39 and dba2e12c7f8e5eee1e8b1565a6e6e49525ba7858.
Thank you for your suggestion.
