### ISSUE TITLE
NATIONAL literals or items are not DISPLAYed correctly

### ISSUE THREAD

**Issue by hanohrs** [opensourcecobol/opensourcecobol4j#49]
I compiled the following program.

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 へろー PIC N(10) VALUE N'へろー'.
       PROCEDURE DIVISION.
           DISPLAY N'はろー'.
           DISPLAY へろー.
           STOP RUN.
```

The result of running the compiled program is the following corrupted characters.
```
$ java HELLO
�͂�[
�ւ�[�@�@�@�@�@�@�@
```

**Comment by yutaro-sakamoto** [comment]
The encoding of displayed characters is SHIFT-JIS.
Since the behavior is in accordance with the specification, it is unfortunate that we will not accept your modification (#50).
