### ISSUE TITLE
can't compile cobol4j 

### ISSUE THREAD

**Issue by alirezag** [opensourcecobol/opensourcecobol4j#508]
when I try to build a ubuntu image to compile and install the framework I get the following error while running `make` command. 

```bash
docker build . -t $SERVICE_NAME -f Dockerfile.ubuntu
```

```dockerfile
FROM ubuntu:24.04

LABEL project="COBOL Modernization"
LABEL maintainer="Alireza Goudarzi <alireza.goudarzi@gmail.com>"

RUN <<EOF
apt update && apt upgrade -y
apt-get install openjdk-21-jdk
apt-get install openjdk-21-jre
apt-get install -y default-jdk build-essential bison flex gettext texinfo libgmp-dev autoconf
curl -L -o opensourcecobol4j-v1.1.2.tar.gz https://github.com/opensourcecobol/opensourcecobol4j/archive/refs/tags/v1.1.2.tar.gz
tar zxvf opensourcecobol4j-v1.1.2.tar.gz
cd opensourcecobol4j-1.1.2
./configure --prefix=/usr/
make
sudo make install
EOF

# copy local directory opensourcecobo4j to /app/opensourcecobo4j
COPY opensourcecobol4j /app/opensourcecobol4j

ENTRYPOINT /bin/bash

```

<img width="770" alt="Screenshot 2024-10-15 at 14 31 24" src="https://github.com/user-attachments/assets/866d3270-6f54-41b8-9c16-b0baebf45dc0">

**Comment by alirezag** [comment]
has anyone been able to compile cobol4j in a docker?

**Comment by yutaro-sakamoto** [comment]
@alirezag 
In #511, I modified C files to resolve this issue.
Please try the latest source code of [develop](https://github.com/opensourcecobol/opensourcecobol4j/tree/develop) branch.

At the end of this month, our team plans to release a new version 1.1.3 which includes this modification.

**Comment by alirezag** [comment]
thanks this seemed to have fixed the issue. I can now compile cobol4j.
