### ISSUE TITLE
How to version-up opensource COBOL 4J?

### ISSUE THREAD

**Issue by tsh-hashimoto** [opensourcecobol/opensourcecobol4j#523]
Hello.

Your team release opensource COBOL 4J every month, thanks.
I would like to update to a newer version if there are attractive features.
So, I want to know how to update this product.

I think that we just need to run the following build and install steps again, isn' it?
(Of course, version number will be changed)
```shell
curl -L -o opensourcecobol4j-v1.1.2.tar.gz https://github.com/opensourcecobol/opensourcecobol4j/archive/refs/tags/v1.1.2.tar.gz
tar zxvf opensourcecobol4j-v1.1.2.tar.gz
cd opensourcecobol4j-1.1.2
./configure --prefix=/usr/
make
make install
```

**Comment by tsh-hashimoto** [comment]
Maybe it is right.

**Comment by yutaro-sakamoto** [comment]
Yes, you should download the latest version and install it if you would like to use the latest version of opensource COBOL 4J.

**Comment by tsh-hashimoto** [comment]
I forgot to close this issue.
