### ISSUE TITLE
The contents in Dev Container environment

### ISSUE THREAD

**Issue by tsh-hashimoto** [opensourcecobol/opensourcecobol4j#532]
Hello.

Thank you for giving Dev Container environment.
At this time, it contains opensource COBOL 4J only.

I have a question.
I want to install [Open COBOL ESQL](https://github.com/opensourcecobol/Open-COBOL-ESQL).
Is it ok to install it this environment with opensource COBOL 4J?

Usually, opensource COBOL 4J is used with [Open COBOL ESQL 4J](https://github.com/opensourcecobol/Open-COBOL-ESQL-4j).
(so it's natural to install Open COBOL ESQL 4J in this container in the future)

My concern is whether installing Open COBOL ESQL and Open COBOL ESQL 4J in the same environment will cause any inconvenience (ex: command conflict.  It seems that both uses `ocesql` when pre-compiling).

This question arises wherever I try to install (not just in containers).

**Comment by yutaro-sakamoto** [comment]
As you pointed out, the precompiler command names of Open COBOL ESQL and Open COBOL ESQL 4J are same.
So If you would like to install both precompilers in the same environment, you first install Open COBOL ESQL and rename ocesql to `ocesqlc` and install Open COBOL ESQL 4J.
(I will change the precompiler command name of Open COBOL ESQL 4J in ther future)

**Comment by yutaro-sakamoto** [comment]
@tsh-hashimoto 
The dev container of opensource COBOL 4J is not suitable to develop Open COBOL ESQL.
In order to develop Open COBOL ESQL, prepare one of Docker, WSL and a linux machine, and install opensource COBOL and Open COBOL ESQL in it.

**Comment by tsh-hashimoto** [comment]
memo

one example, we should rename `/usr/bin/ocesql` -> `/usr/bin/ocesql4j`, or `/usr/bin/ocesql` -> `/usr/bin/ocesqlc` to avoid conflict.
