### ISSUE TITLE
Fail to compile a HELLO.cbl

### ISSUE THREAD

**Issue by alirezag** [opensourcecobol/opensourcecobol4j#537]
I am able to compile cobol4j but it seems like I can't compile a basic program. Not sure if it is a dilect compatibility or a encoding issue: 

`HELLO.cbl`
```cbl
IDENTIFICATION DIVISION.
PROGRAM-ID. hello.
PROCEDURE DIVISION.
DISPLAY "Hello World!".
STOP RUN.
```

```bash
root@c0b52ef193c5:~/test# cobj HELLO.cbl 
HELLO.cbl:1: Error: Invalid indicator 'F' at column 7
HELLO.cbl:1: Error: syntax error, unexpected end of file, expecting PROGRAM_ID or FUNCTION_ID
```
cc @royxue

**Comment by yutaro-sakamoto** [comment]
@alirezag 
Please use the following program instead.
`hello.cbl`
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. hello.
       PROCEDURE DIVISION.
       DISPLAY "Hello World!".
       STOP RUN.
```
COBOL compilers normally ignore the first 6 characters and 73th and succeeding characters of each line.
If the seventh character of a line is '*', then the 8th and succeeding characters of that line are comments.
Thus, the following program is equivalent to the one above.
```cobol
       IDENTIFICATION DIVISION.
      *comment 1
       PROGRAM-ID. hello.
       PROCEDURE DIVISION.
      *comment 2
       DISPLAY "Hello World!".
       STOP RUN.
```
If you run `cobj -free hello.cbl`, then the compiler accepts the following program.
```cobol
IDENTIFICATION DIVISION.
PROGRAM-ID. hello.
PROCEDURE DIVISION.
DISPLAY "Hello World!".
STOP RUN.
```

**Comment by alirezag** [comment]
thanks yes that fixed it.
